project:
  type: website
  output-dir: docs

website:
  title: "Ava Santos-Volpe"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Data Visualization"
        menu:
          - href: australian_frogs.qmd
            text: "Australian Frogs"
          - href: animalshelter.qmd
            text: "Long Beach Animal Shelter"
      - href: text_analysis.qmd
        text: "Text Analysis"
      - href: simulation_study.qmd
        text: "A Simulation Study"
      - href: data_ethics.qmd
        text: "Data Ethics"
      - href: SQL.qmd
        text: "SQL"
      - href: presentation.qmd
        text: "Presentation"

format:
  html: 
    theme: brite
    css: styles.css
    toc: true
    page-layout: full

editor: source
